CREATE DATABASE EMOTION_BASED_CHATBOT

CREATE TABLE _USER(USER_ID INT PRIMARY KEY IDENTITY(1,1),USER_NAME VARCHAR(50), EMAIL VARCHAR(10), PASSWORD VARCHAR(50))

CREATE TABLE BOT(ID INT PRIMARY KEY IDENTITY(1,1), CHARACTER VARCHAR(20))

CREATE TABLE CHAT_SESSION(SESSION_ID INT PRIMARY KEY IDENTITY(1,1), TITLE NVARCHAR(max), CREATION_DATE DATE,UserId int FOREIGN KEY REFERENCES _USER(USER_ID),BOT_ID int FOREIGN KEY REFERENCES BOT(ID))

CREATE TABLE CHAT_MESSAGES(MESSAGE_ID INT PRIMARY KEY IDENTITY(1,1), EMOTION VARCHAR(10), SOURCE VARCHAR(50), TEXT nvarchar(max), ENTRY_DATE DATETIME, SESSION_ID INT FOREIGN KEY REFERENCES CHAT_SESSION(SESSION_ID))